/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppPerfisRouteImport } from './routes/_app.perfis'
import { Route as AppPendentesRouteImport } from './routes/_app.pendentes'
import { Route as AppPagasRouteImport } from './routes/_app.pagas'
import { Route as AppNovaRouteImport } from './routes/_app.nova'
import { Route as AppIaRouteImport } from './routes/_app.ia'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCategoriasRouteImport } from './routes/_app.categorias'
import { Route as AppContaIdRouteImport } from './routes/_app.conta.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfisRoute = AppPerfisRouteImport.update({
  id: '/perfis',
  path: '/perfis',
  getParentRoute: () => AppRoute,
} as any)
const AppPendentesRoute = AppPendentesRouteImport.update({
  id: '/pendentes',
  path: '/pendentes',
  getParentRoute: () => AppRoute,
} as any)
const AppPagasRoute = AppPagasRouteImport.update({
  id: '/pagas',
  path: '/pagas',
  getParentRoute: () => AppRoute,
} as any)
const AppNovaRoute = AppNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => AppRoute,
} as any)
const AppIaRoute = AppIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriasRoute = AppCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AppRoute,
} as any)
const AppContaIdRoute = AppContaIdRouteImport.update({
  id: '/conta/$id',
  path: '/conta/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/categorias': typeof AppCategoriasRoute
  '/dashboard': typeof AppDashboardRoute
  '/ia': typeof AppIaRoute
  '/nova': typeof AppNovaRoute
  '/pagas': typeof AppPagasRoute
  '/pendentes': typeof AppPendentesRoute
  '/perfis': typeof AppPerfisRoute
  '/conta/$id': typeof AppContaIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/categorias': typeof AppCategoriasRoute
  '/dashboard': typeof AppDashboardRoute
  '/ia': typeof AppIaRoute
  '/nova': typeof AppNovaRoute
  '/pagas': typeof AppPagasRoute
  '/pendentes': typeof AppPendentesRoute
  '/perfis': typeof AppPerfisRoute
  '/': typeof AppIndexRoute
  '/conta/$id': typeof AppContaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/categorias': typeof AppCategoriasRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/ia': typeof AppIaRoute
  '/_app/nova': typeof AppNovaRoute
  '/_app/pagas': typeof AppPagasRoute
  '/_app/pendentes': typeof AppPendentesRoute
  '/_app/perfis': typeof AppPerfisRoute
  '/_app/': typeof AppIndexRoute
  '/_app/conta/$id': typeof AppContaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/categorias'
    | '/dashboard'
    | '/ia'
    | '/nova'
    | '/pagas'
    | '/pendentes'
    | '/perfis'
    | '/conta/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/sitemap.xml'
    | '/categorias'
    | '/dashboard'
    | '/ia'
    | '/nova'
    | '/pagas'
    | '/pendentes'
    | '/perfis'
    | '/'
    | '/conta/$id'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/sitemap.xml'
    | '/_app/categorias'
    | '/_app/dashboard'
    | '/_app/ia'
    | '/_app/nova'
    | '/_app/pagas'
    | '/_app/pendentes'
    | '/_app/perfis'
    | '/_app/'
    | '/_app/conta/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfis': {
      id: '/_app/perfis'
      path: '/perfis'
      fullPath: '/perfis'
      preLoaderRoute: typeof AppPerfisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pendentes': {
      id: '/_app/pendentes'
      path: '/pendentes'
      fullPath: '/pendentes'
      preLoaderRoute: typeof AppPendentesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pagas': {
      id: '/_app/pagas'
      path: '/pagas'
      fullPath: '/pagas'
      preLoaderRoute: typeof AppPagasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nova': {
      id: '/_app/nova'
      path: '/nova'
      fullPath: '/nova'
      preLoaderRoute: typeof AppNovaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ia': {
      id: '/_app/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof AppIaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categorias': {
      id: '/_app/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AppCategoriasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/conta/$id': {
      id: '/_app/conta/$id'
      path: '/conta/$id'
      fullPath: '/conta/$id'
      preLoaderRoute: typeof AppContaIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCategoriasRoute: typeof AppCategoriasRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppIaRoute: typeof AppIaRoute
  AppNovaRoute: typeof AppNovaRoute
  AppPagasRoute: typeof AppPagasRoute
  AppPendentesRoute: typeof AppPendentesRoute
  AppPerfisRoute: typeof AppPerfisRoute
  AppIndexRoute: typeof AppIndexRoute
  AppContaIdRoute: typeof AppContaIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCategoriasRoute: AppCategoriasRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppIaRoute: AppIaRoute,
  AppNovaRoute: AppNovaRoute,
  AppPagasRoute: AppPagasRoute,
  AppPendentesRoute: AppPendentesRoute,
  AppPerfisRoute: AppPerfisRoute,
  AppIndexRoute: AppIndexRoute,
  AppContaIdRoute: AppContaIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
